language: go
sudo: false
go:
  - 1.8

services:
  - postgresql

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - psql -U postgres < schema/schema.sql

os:
  - linux

script:
  - go build -race
  - go test -v ./... 
  - go vet 
  - $HOME/gopath/bin/goveralls -service=travis-ci
